name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.12]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install dependencies
        run: uv sync --locked --dev --python ${{ matrix.python-version }}

      - name: Style Check
        run: |
          uv run black --check authsign/*.py
          uv run black --check tests/*.py

      - name: Lint Check
        run: uv run pylint --rcfile=pylint.ini authsign/

      - name: run pebble in background
        run: docker run -e PEBBLE_WFE_NONCEREJECT=0 -d --network "host" ghcr.io/letsencrypt/pebble:latest

      - name: add custom domain to /etc/hosts
        run: echo "127.0.0.1 localhost.test" | sudo tee -a /etc/hosts

      - name: run tests
        run: uv run py.test --domain localhost.test --maxfail 1
